PATCH localhost:8080/api/user/password
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMzAyMTkyNjI4OTE1NTIzNTg0Iiwicm9sZSI6ImFhc3MiLCJpYXQiOjE3MzA1MzgxMzMsImV4cCI6MTczMDYyNDUzM30.7HQ-A_CDdOQeA7sy4t6eEEkdfMOCrKrfFz_0kBoaS50
Content-Type: application/json

{
  "password": "ajda2"
}