### getUsers
GET localhost:8080/api/admin/users

### getUser
GET localhost:8080/api/admin/users/100
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjEiLCJpYXQiOjE3MzE4NDQyNDksImV4cCI6MTczMTkzMDY0OX0.6iWHrTMo2q1ZnQdqsriLHHTuzw3IpbOtBP51vFmml0g
### error
GET localhost:8080/api/admin/users/1001
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjEiLCJpYXQiOjE3MzE4NDQyNDksImV4cCI6MTczMTkzMDY0OX0.6iWHrTMo2q1ZnQdqsriLHHTuzw3IpbOtBP51vFmml0g

### user token
GET localhost:8080/api/admin/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxIiwicm9sZSI6InNxV2YiLCJpYXQiOjE3MzE4NDQwNTUsImV4cCI6MTczMTkzMDQ1NX0.zl4htWbvNEpx9jTSlrksWbAkOjWTgc7EdO7RMCrEKQ4
### admin token
GET localhost:8080/api/admin/users
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3FXZiIsInVpZCI6IjEiLCJpYXQiOjE3Mjk4MjA1NTMsImV4cCI6MTcyOTkwNjk1M30.jSdCcE2toDMkllZMOo8ncbHjG_JYRjT76fxe_MlpJcM