spring:
  datasource:
    url: 'jdbc:mysql://120.46.159.231:3306/2022223008?createDatabaseIfNotExist=true'
    username: 2022223008
    password: 2022223008
  sql:
    init:
      mode: always
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: warn
    org:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
my:
  secretkey: assdf