spring:
  datasource:
    url: jdbc:mysql://120.46.159.231:3306/2022223008
    username: 2022223008
    password: 2022223008
  sql:
    init:
      mode: always # 每次启动均执行数据库初始化脚本

logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'